# Generated by Django 3.2.7 on 2021-10-01 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imgage', models.ImageField(upload_to='', verbose_name='images/')),
                ('subtitle', models.TextField(null=True)),
                ('describtion', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('situation', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1)),
            ],
        ),
    ]
