# Generated by Django 3.2.8 on 2021-10-28 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی')),
                ('situation', models.BooleanField(default=True, verbose_name='آیا نمایش ٔداده شود؟')),
                ('position', models.IntegerField(verbose_name='موقعیت')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
                'ordering': ['parent__id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='سرتیتر')),
                ('imgage', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('subtitle', models.TextField(verbose_name='چکیده مطلب')),
                ('describtion', models.TextField(verbose_name='مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس پست')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان تولید')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('author', models.CharField(max_length=100, verbose_name='نوشته شده توسط')),
                ('situation', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشرشده')], max_length=1, verbose_name='وضعیت پست')),
                ('category', models.ManyToManyField(related_name='article', to='blog.Category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['title', 'situation'],
            },
        ),
    ]
