# Generated by Django 3.2.8 on 2021-11-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='situation',
            field=models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشرشده'), ('i', 'درحال\u200cبررسی'), ('b', 'برگشت\u200cداده\u200cشده')], max_length=1, verbose_name='وضعیت پست'),
        ),
    ]
